version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: recipes
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  dbclient:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL : test@gmail.com
      PGADMIN_DEFAULT_PASSWORD : p
    ports:
      - "8889:80"